version: '3'
services:
  app:
    build: .
    restart: always
    ports:
      - "${PORT:?err}:${PORT:?err}"
    volumes:
      - "./${DATA_DIRPATH:?err}:/root/main/${DATA_DIRPATH:?err}"
    environment:
      IS_DOCKER: true
    env_file:
      - .env
